### PR TITLE
Implement reshuffle articles

### PR DESCRIPTION
**Pull request by SashaLoayza**
## Overview

Implemented reshuffling of articles, method called 'getShuffledArticlesByPublicationSlugs' in ArticleRepos and ArticleResolvers.

## Changes Made

Return a list of Article objects sorted by date, but each publisher has to show up at least once before articles by the same publisher shows up again
e.g. :
publisher 1 has articles 1.1 (published jan 1), 1.2 (published jan 6)
publisher 2 has articles 2.1 (published jan 5), 2.2 (published jan 4)
publisher 3 has articles 3.1 (published jan 2), 3.2 (published jan 3)
getShuffledArticlesByPublicationSlugs should return [1.1, 3.1, 2.1, 3.2, 2.2, 1.2]

The time range that articles should be retrieved from can be specified with timeRange (integer representing months since current date).

The query takes required parameter of a list of publication slugs (strings) called 'slugs', and optional parameters of 'limit', 'offset', and 'timeRange'.

## Test Coverage

Manually tested locally on GraphQL playground. Tested with two and three different publication slugs.

## Next Steps 

May need to add resolvers for querying by list of publication IDs, which will be a simple map to this function.

### CODE REVIEW

**Review by snajima — APPROVED** [review]
lgtm, let's just address the same issues as #66, then get this merged!

**Comment by snajima** [comment]
for the sake of development we're skipping jest cases for this endpoint – also the tests would more so assess the algorithm rather than the backend/db queries functioning (since that's covered in the general get articles test cases). good point tho ! @isaachan100

**Review by snajima — CHANGES_REQUESTED** [review]
for the sake of development we're skipping test cases for this endpoint – also since the tests would more so assess the shuffling algorithm rather than the backend/db queries functioning (bc that's already covered in the get all articles tests). good point tho! @isaachan100 

i'm gonna need you to revert your changes in `.eslintrc.js`, `package-lock.json`, and `package.json` if these were addressed by isaac though :)

**Review by isaachan100 — APPROVED** [review]
looks good!

**Review by isaachan100 — COMMENTED** [review]
lgtm!

**Review by snajima — APPROVED** [review]
let's go sasha!!!

**Review by isaachan100 — COMMENTED** [review]
lgtm!

**Review by isaachan100 — APPROVED** [review]
looks good!

**Pull request merged**
